name: AI Sandbox Guard

on:
  push:
    branches:
      - "feature/ai-*"

jobs:
  sandbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps
      - name: Guards
        run: pnpm run brand:guard
      - name: Verify hue spec
        run: pnpm run verify:hue
      - name: Brand tests
        run: pnpm run test:brand
      - name: Build
        run: pnpm run build
