name: Brand Guard

on: [pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - name: Brand Guard
        run: pnpm brand:guard

      - name: Verify Hue
        run: pnpm verify:hue

      - name: Brand Tests
        run: pnpm test:brand
